### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by 95karan** [dhteodoro/sus-openehr-builder#2]
Exception in thread "main" java.lang.NullPointerException
        at br.uerj.lampada.openehr.susbuilder.builder.CompositionManager.connectDB(CompositionManager.java:138)
        at br.uerj.lampada.openehr.susbuilder.builder.CompositionManager.<init>(CompositionManager.java:49)
        at br.uerj.lampada.openehr.susbuilder.EHRGenerator.generateEHRs(EHRGenerator.java:107)
        at br.uerj.lampada.openehr.susbuilder.EHRGenerator.main(EHRGenerator.java:379)

**Comment by adityabangia** [comment]
Hi, were you able to resolve this issue?

**Comment by sayan801** [comment]
@95karan this is db connection problem. Please provide your db credentials in the builder.properties file 

db.url=jdbc:postgresql://localhost:5432/DB_NAME
db.username=DB_USER_NAME
db.password=DB_PASSWORD

and then update your postgres dependency ( **org.postgresql** ) version to **42.2.24** in pom.xml

We have added following dependencies and it works..

```
<dependency>
                        <groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.2.24</version>
</dependency>
```
